version: "3.9"

networks:
  safefi-network:
    driver: bridge

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: safefi-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-defi_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-usersafety}
      POSTGRES_DB: ${POSTGRES_DB:-defi_risk}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - safefi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-defi_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MLflow for Model Tracking
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.2
    container_name: safefi-mlflow
    restart: unless-stopped
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow --default-artifact-root /mlflow
    ports:
      - "${MLFLOW_PORT:-5000}:5000"
    volumes:
      - mlruns:/mlflow
    networks:
      - safefi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: safefi-api
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-defi_user}:${POSTGRES_PASSWORD:-usersafety}@db:5432/${POSTGRES_DB:-defi_risk}
      MLFLOW_TRACKING_URI: http://mlflow:5000
      ENVIRONMENT: ${ENVIRONMENT:-production}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:5173,http://localhost:80}
      # LLM Configuration
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://localhost:11434}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-tinyllama}
      # Email Configuration
      EMAIL_ALERTS_ENABLED: ${EMAIL_ALERTS_ENABLED:-false}
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM:-safefi@example.com}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-SafeFi Alert System}
    depends_on:
      db:
        condition: service_healthy
      mlflow:
        condition: service_healthy
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./backend/models:/app/models
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
    networks:
      - safefi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: safefi-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - api
    networks:
      - safefi-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  pgdata:
    driver: local
  mlruns:
    driver: local



