version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: defi_user
      POSTGRES_PASSWORD: usersafety
      POSTGRES_DB: defi_risk_assessment
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.2
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow --default-artifact-root /mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlruns:/mlflow

  api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://defi_user:usersafety@db:5432/defi_risk_assessment
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      - db
      - mlflow
    ports:
      - "8000:8000"

volumes:
  pgdata:
  mlruns:



